"""Versioned JSON Schemas for every workspace file live in this directory.

They are generated by :mod:`areao1.schemas` from the pydantic models; regenerate after changing
a model with ``python -m areao1.schemas``.
"""

from __future__ import annotations

from pathlib import Path

SCHEMA_DIR = Path(__file__).parent


def schema_files() -> list[Path]:
    return sorted(SCHEMA_DIR.glob("*.schema.json"))
